version: '3.5'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - '3001'
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development
    command: node api.js
    ports:
      - '3001:3001'
